-- =========================================================================
-- 1. SEGURIDAD Y ACCESOS (MODELO CENTRALIZADO)
-- =========================================================================

CREATE TABLE Rol (
    rol_id NUMBER(2) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR2(30) UNIQUE NOT NULL, 
    descripcion VARCHAR2(150),
    nivel_acceso NUMBER(1) DEFAULT 1,
    CONSTRAINT pk_rol PRIMARY KEY (rol_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Usuario_Sistema (
    usuario_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(64) NOT NULL, -- SHA-256
    email VARCHAR2(100) UNIQUE,
    rol_id NUMBER(2) NOT NULL,
    estado NUMBER(1) DEFAULT 1 CHECK (estado IN (0, 1)),
    
    -- CAMBIO V3.2: Foto de Perfil Biométrica
    foto_perfil BLOB,
    foto_mime_type VARCHAR2(50), -- Ej: 'image/png'
    foto_nombre VARCHAR2(100),
    
    -- Auditoría
    ultimo_acceso TIMESTAMP,
    intentos_fallidos NUMBER(2) DEFAULT 0,
    fecha_creacion DATE DEFAULT SYSDATE,
    CONSTRAINT pk_usuario_sistema PRIMARY KEY (usuario_id),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES Rol(rol_id)
) TABLESPACE ts_wasimikuna;

INSERT INTO Rol (nombre, descripcion, nivel_acceso) VALUES ('ADMIN_SYS', 'Administrador del Sistema', 9);
INSERT INTO Rol (nombre, descripcion, nivel_acceso) VALUES ('MONITOR_CALIDAD', 'Auditor de campo y calidad', 5);
INSERT INTO Rol (nombre, descripcion, nivel_acceso) VALUES ('DIRECTOR_COLEGIO', 'Responsable de IE', 3);
INSERT INTO Rol (nombre, descripcion, nivel_acceso) VALUES ('PROVEEDOR', 'Afiliado logístico o agricultor', 3);
INSERT INTO Rol (nombre, descripcion, nivel_acceso) VALUES ('AUDITOR_OCI', 'Órgano de Control Institucional', 1);

-- =========================================================================
-- 2. TABLAS DE ACTORES
-- =========================================================================

CREATE TABLE Institucion_Educativa (
    institucion_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id NUMBER(10) NOT NULL,
    codigo_modular CHAR(7) NOT NULL, 
    anexo CHAR(1) DEFAULT '0',
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(200),
    departamento VARCHAR2(50),
    provincia VARCHAR2(50),
    distrito VARCHAR2(50),
    ubigeo CHAR(6),
    fecha_registro DATE DEFAULT SYSDATE,
    estado_activo NUMBER(1) DEFAULT 1,
    CONSTRAINT pk_institucion_educativa PRIMARY KEY (institucion_id),
    CONSTRAINT uq_codigo_modular UNIQUE (codigo_modular, anexo),
    CONSTRAINT fk_ie_usuario FOREIGN KEY (usuario_id) REFERENCES Usuario_Sistema(usuario_id),
    CONSTRAINT uq_ie_usuario UNIQUE (usuario_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Afiliado (
    afiliado_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id NUMBER(10) NOT NULL,
    tipo VARCHAR2(15) CHECK (tipo IN ('DISTRIBUIDOR', 'PROVEEDOR_LOCAL', 'AGRICULTOR')),
    ruc CHAR(11) NOT NULL,
    razon_social VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(200),
    contacto_nombre VARCHAR2(100),
    contacto_telefono CHAR(9),
    estado NUMBER(1) DEFAULT 1 CHECK (estado IN (0, 1)),
    calificacion_sanitaria NUMBER(3) DEFAULT 100,
    fecha_creacion DATE DEFAULT SYSDATE,
    CONSTRAINT pk_afiliado PRIMARY KEY (afiliado_id),
    CONSTRAINT uq_afiliado_ruc UNIQUE (ruc),
    CONSTRAINT fk_afiliado_usuario FOREIGN KEY (usuario_id) REFERENCES Usuario_Sistema(usuario_id),
    CONSTRAINT uq_afiliado_usuario UNIQUE (usuario_id)
) TABLESPACE ts_wasimikuna;

-- =========================================================================
-- 3. TABLAS MAESTRAS DE SOPORTE
-- =========================================================================

CREATE TABLE Producto (
    producto_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR2(150) NOT NULL,
    unidad_medida VARCHAR2(10), 
    categoria VARCHAR2(20) CHECK (categoria IN ('PERECIBLE', 'NO_PERECIBLE', 'CARNE_FRESCA', 'VERDURA', 'LACTEO')),
    vida_util_dias NUMBER(4),
    requiere_refrigeracion NUMBER(1) DEFAULT 0 CHECK (requiere_refrigeracion IN (0, 1)),
    descripcion VARCHAR2(200),
    CONSTRAINT pk_producto PRIMARY KEY (producto_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Plato (
    plato_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    aporte_calorico NUMBER(6,2),
    aporte_proteico NUMBER(6,2),
    aporte_hierro NUMBER(6,2),
    region_origen VARCHAR2(50),
    receta_texto CLOB,
    CONSTRAINT pk_plato PRIMARY KEY (plato_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Comite_Gestion (
    miembro_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institucion_id NUMBER(10) NOT NULL,
    dni CHAR(8) NOT NULL,
    nombre_completo VARCHAR2(150) NOT NULL,
    cargo VARCHAR2(50) CHECK (cargo IN ('PRESIDENTE', 'SECRETARIO', 'VOCAL', 'PADRE_VIGILANTE')),
    telefono CHAR(9),
    fecha_inicio_vigencia DATE DEFAULT SYSDATE,
    fecha_fin_vigencia DATE,
    estado_activo NUMBER(1) DEFAULT 1,
    CONSTRAINT pk_comite PRIMARY KEY (miembro_id),
    CONSTRAINT fk_comite_ie FOREIGN KEY (institucion_id) 
        REFERENCES Institucion_Educativa(institucion_id),
    CONSTRAINT uq_dni_comite UNIQUE (dni, institucion_id)
) TABLESPACE ts_wasimikuna;

-- =========================================================================
-- 4. MÓDULO TRANSACCIONAL
-- =========================================================================

CREATE TABLE Orden_Compra (
    orden_compra_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    afiliado_id NUMBER(10) NOT NULL,
    fecha_emision DATE DEFAULT SYSDATE,
    estado NUMBER(1) DEFAULT 0 CHECK (estado IN (0, 1, 2, 3)), 
    total NUMBER(12, 2) DEFAULT 0,
    fecha_entrega_prevista DATE,
    usuario_creacion_id NUMBER(10),
    fecha_modificacion DATE,
    CONSTRAINT pk_orden_compra PRIMARY KEY (orden_compra_id),
    CONSTRAINT fk_orden_afiliado FOREIGN KEY (afiliado_id) REFERENCES Afiliado(afiliado_id),
    CONSTRAINT fk_orden_user_crea FOREIGN KEY (usuario_creacion_id) REFERENCES Usuario_Sistema(usuario_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Detalle_Orden (
    detalle_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    orden_compra_id NUMBER(10) NOT NULL,
    producto_id NUMBER(10) NOT NULL,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_detalle_orden PRIMARY KEY (detalle_id),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
    CONSTRAINT fk_detalle_orden FOREIGN KEY (orden_compra_id) REFERENCES Orden_Compra(orden_compra_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Envio (
    envio_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    orden_compra_id NUMBER(10) NOT NULL,
    institucion_id NUMBER(10) NOT NULL,
    conductor_nombre VARCHAR2(100),
    placa_vehiculo VARCHAR2(10),
    fecha_salida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_envio VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (estado_envio IN ('PENDIENTE', 'EN_RUTA', 'ENTREGADO', 'DEVUELTO')),
    usuario_despacho_id NUMBER(10),
    CONSTRAINT pk_envio PRIMARY KEY (envio_id),
    CONSTRAINT fk_envio_orden FOREIGN KEY (orden_compra_id) REFERENCES Orden_Compra(orden_compra_id),
    CONSTRAINT fk_envio_institucion FOREIGN KEY (institucion_id) REFERENCES Institucion_Educativa(institucion_id),
    CONSTRAINT fk_envio_user FOREIGN KEY (usuario_despacho_id) REFERENCES Usuario_Sistema(usuario_id)
) TABLESPACE ts_wasimikuna;

-- =========================================================================
-- 5. MÓDULO DE RECEPCIÓN Y CALIDAD
-- =========================================================================

CREATE TABLE Recepcion (
    recepcion_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    envio_id NUMBER(10) NOT NULL,
    comite_miembro_id NUMBER(10),
    fecha_recepcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_conformidad VARCHAR2(20) CHECK (estado_conformidad IN ('CONFORME', 'OBSERVADO', 'RECHAZADO')),
    observaciones_generales VARCHAR2(400),
    -- Almacenamiento BLOB para Acta
    acta_archivo BLOB,
    acta_mime_type VARCHAR2(50), 
    acta_nombre_archivo VARCHAR2(100),
    CONSTRAINT pk_recepcion PRIMARY KEY (recepcion_id),
    CONSTRAINT fk_recepcion_envio FOREIGN KEY (envio_id) REFERENCES Envio(envio_id),
    CONSTRAINT fk_recepcion_comite FOREIGN KEY (comite_miembro_id) REFERENCES Comite_Gestion(miembro_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Detalle_Recepcion (
    det_recepcion_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recepcion_id NUMBER(10) NOT NULL,
    producto_id NUMBER(10) NOT NULL,
    lote_fabricacion VARCHAR2(50) NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    cantidad_recibida INTEGER NOT NULL,
    cantidad_rechazada INTEGER DEFAULT 0,
    motivo_rechazo VARCHAR2(100),
    -- Almacenamiento BLOB para Evidencia (Foto)
    evidencia_archivo BLOB,
    evidencia_mime_type VARCHAR2(50),
    evidencia_nombre_archivo VARCHAR2(100),
    CONSTRAINT pk_det_recepcion PRIMARY KEY (det_recepcion_id),
    CONSTRAINT fk_det_rec_cab FOREIGN KEY (recepcion_id) REFERENCES Recepcion(recepcion_id),
    CONSTRAINT fk_det_rec_prod FOREIGN KEY (producto_id) REFERENCES Producto(producto_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Incidencia_Sanitaria (
    incidencia_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institucion_id NUMBER(10) NOT NULL,
    producto_id NUMBER(10),
    lote_afectado VARCHAR2(50),
    tipo_riesgo VARCHAR2(30) CHECK (tipo_riesgo IN ('OLOR_EXTRAÑO', 'ENVASE_DAÑADO', 'FECHA_VENCIDA', 'CUERPO_EXTRAÑO', 'INTOXICACION')),
    descripcion_detallada VARCHAR2(400),
    fecha_reporte TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_atencion VARCHAR2(20) DEFAULT 'REPORTADO' CHECK (estado_atencion IN ('REPORTADO', 'EN_EVALUACION', 'CONFIRMADO', 'DESCARTADO')),
    accion_tomada VARCHAR2(200),
    usuario_reportante_id NUMBER(10),
    monitor_asignado_id NUMBER(10),
    CONSTRAINT pk_incidencia PRIMARY KEY (incidencia_id),
    CONSTRAINT fk_inc_ie FOREIGN KEY (institucion_id) REFERENCES Institucion_Educativa(institucion_id),
    CONSTRAINT fk_inc_prod FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
    CONSTRAINT fk_inc_user FOREIGN KEY (usuario_reportante_id) REFERENCES Comite_Gestion(miembro_id),
    CONSTRAINT fk_inc_monitor FOREIGN KEY (monitor_asignado_id) REFERENCES Usuario_Sistema(usuario_id)
) TABLESPACE ts_wasimikuna;

-- =========================================================================
-- 6. MÓDULO DE CONSUMO (Menús)
-- =========================================================================

CREATE TABLE Programacion_Menu (
    programacion_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institucion_id NUMBER(10) NOT NULL,
    fecha_consumo DATE NOT NULL,
    plato_id NUMBER(10) NOT NULL,
    cantidad_raciones NUMBER(5) NOT NULL,
    estado_preparacion VARCHAR2(20) DEFAULT 'PLANIFICADO' CHECK (estado_preparacion IN ('PLANIFICADO', 'COCINADO', 'SERVIDO')),
    fecha_registro DATE DEFAULT SYSDATE,
    CONSTRAINT pk_programacion PRIMARY KEY (programacion_id),
    CONSTRAINT fk_prog_ie FOREIGN KEY (institucion_id) REFERENCES Institucion_Educativa(institucion_id),
    CONSTRAINT fk_prog_plato FOREIGN KEY (plato_id) REFERENCES Plato(plato_id)
) TABLESPACE ts_wasimikuna;

CREATE TABLE Receta_Producto (
    receta_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plato_id NUMBER(10) NOT NULL,
    producto_id NUMBER(10) NOT NULL,
    cantidad_por_racion NUMBER(8,4) NOT NULL,
    CONSTRAINT pk_receta PRIMARY KEY (receta_id),
    CONSTRAINT fk_rec_plato FOREIGN KEY (plato_id) REFERENCES Plato(plato_id),
    CONSTRAINT fk_rec_prod FOREIGN KEY (producto_id) REFERENCES Producto(producto_id)
) TABLESPACE ts_wasimikuna;

-- =========================================================================
-- 7. AUDITORÍA
-- =========================================================================

CREATE TABLE Auditoria_Sistema (
    auditoria_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR2(50),
    accion VARCHAR2(10),
    id_registro NUMBER,
    usuario_db VARCHAR2(50),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    datos_anteriores VARCHAR2(4000)
) TABLESPACE ts_wasimikuna;

-- =========================================================================
-- 8. ÍNDICES DE RENDIMIENTO
-- =========================================================================

CREATE INDEX idx_usuario_rol ON Usuario_Sistema(rol_id);
CREATE INDEX idx_ie_usuario ON Institucion_Educativa(usuario_id);
CREATE INDEX idx_afiliado_usuario ON Afiliado(usuario_id);

CREATE INDEX idx_comite_institucion ON Comite_Gestion(institucion_id);
CREATE INDEX idx_orden_afiliado ON Orden_Compra(afiliado_id);
CREATE INDEX idx_detalle_orden_prod ON Detalle_Orden(producto_id);
CREATE INDEX idx_detalle_orden_cab ON Detalle_Orden(orden_compra_id);
CREATE INDEX idx_envio_orden ON Envio(orden_compra_id);
CREATE INDEX idx_envio_inst ON Envio(institucion_id);
CREATE INDEX idx_recepcion_envio ON Recepcion(envio_id);
CREATE INDEX idx_recepcion_comite ON Recepcion(comite_miembro_id);
CREATE INDEX idx_det_recep_cab ON Detalle_Recepcion(recepcion_id);
CREATE INDEX idx_det_recep_prod ON Detalle_Recepcion(producto_id);
CREATE INDEX idx_incidencia_inst ON Incidencia_Sanitaria(institucion_id);
CREATE INDEX idx_prog_inst ON Programacion_Menu(institucion_id);
CREATE INDEX idx_prog_plato ON Programacion_Menu(plato_id);
CREATE INDEX idx_receta_plato ON Receta_Producto(plato_id);
CREATE INDEX idx_receta_prod ON Receta_Producto(producto_id);

CREATE INDEX idx_inst_ubigeo ON Institucion_Educativa(ubigeo);
CREATE INDEX idx_inst_nombre ON Institucion_Educativa(nombre);
CREATE INDEX idx_afiliado_tipo ON Afiliado(tipo);
CREATE INDEX idx_producto_nombre ON Producto(nombre);
CREATE INDEX idx_envio_fecha ON Envio(fecha_salida);
CREATE INDEX idx_prog_fecha ON Programacion_Menu(fecha_consumo);

CREATE INDEX idx_det_recep_lote ON Detalle_Recepcion(lote_fabricacion);
CREATE INDEX idx_incidencia_lote ON Incidencia_Sanitaria(lote_afectado);
CREATE INDEX idx_det_recep_venc ON Detalle_Recepcion(fecha_vencimiento);

-- =========================================================================
-- 9. VISTAS ESTRATÉGICAS
-- =========================================================================

CREATE OR REPLACE VIEW VW_KARDEX_ENTRADAS AS
SELECT 
    ie.nombre AS colegio,
    p.nombre AS producto,
    dr.lote_fabricacion,
    dr.fecha_vencimiento,
    SUM(dr.cantidad_recibida) AS total_ingresado,
    MAX(r.fecha_recepcion) AS ultima_entrada
FROM Detalle_Recepcion dr
JOIN Recepcion r ON dr.recepcion_id = r.recepcion_id
JOIN Envio e ON r.envio_id = e.envio_id
JOIN Institucion_Educativa ie ON e.institucion_id = ie.institucion_id
JOIN Producto p ON dr.producto_id = p.producto_id
WHERE r.estado_conformidad = 'CONFORME'
GROUP BY ie.nombre, p.nombre, dr.lote_fabricacion, dr.fecha_vencimiento;

CREATE OR REPLACE VIEW VW_CONSUMO_MENUS AS
SELECT 
    pm.institucion_id,
    rp.producto_id,
    SUM(pm.cantidad_raciones * rp.cantidad_por_racion) AS total_consumido
FROM Programacion_Menu pm
JOIN Receta_Producto rp ON pm.plato_id = rp.plato_id
WHERE pm.estado_preparacion = 'SERVIDO'
GROUP BY pm.institucion_id, rp.producto_id;

CREATE OR REPLACE VIEW VW_STOCK_ACTUAL AS
SELECT 
    ie.nombre AS colegio,
    p.nombre AS producto,
    NVL(SUM(dr.cantidad_recibida), 0) AS total_ingresos,
    NVL((SELECT total_consumido 
         FROM VW_CONSUMO_MENUS cm 
         WHERE cm.institucion_id = ie.institucion_id 
           AND cm.producto_id = p.producto_id), 0) AS total_salidas,
    (NVL(SUM(dr.cantidad_recibida), 0) - 
     NVL((SELECT total_consumido 
          FROM VW_CONSUMO_MENUS cm 
          WHERE cm.institucion_id = ie.institucion_id 
            AND cm.producto_id = p.producto_id), 0)) AS stock_actual
FROM Detalle_Recepcion dr
JOIN Recepcion r ON dr.recepcion_id = r.recepcion_id
JOIN Envio e ON r.envio_id = e.envio_id
JOIN Institucion_Educativa ie ON e.institucion_id = ie.institucion_id
JOIN Producto p ON dr.producto_id = p.producto_id
WHERE r.estado_conformidad = 'CONFORME'
GROUP BY ie.institucion_id, ie.nombre, p.producto_id, p.nombre;

-- =========================================================================
-- 10. TRIGGERS
-- =========================================================================

CREATE OR REPLACE TRIGGER trg_audit_envio
AFTER UPDATE OF estado_envio ON Envio
FOR EACH ROW
BEGIN
    INSERT INTO Auditoria_Sistema (tabla_afectada, accion, id_registro, usuario_db, datos_anteriores)
    VALUES ('ENVIO', 'UPDATE', :OLD.envio_id, USER, 'Estado anterior: ' || :OLD.estado_envio);
END;
/

CREATE OR REPLACE TRIGGER trg_bloqueo_vencidos
BEFORE INSERT ON Detalle_Recepcion
FOR EACH ROW
BEGIN
    IF :NEW.fecha_vencimiento < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20002, 'ALERTA WASI MIKUNA: No se puede recepcionar productos con fecha de vencimiento pasada.');
    END IF;
END;
/

-- =========================================================================
-- 11. PROCEDIMIENTOS Y FUNCIONES (LÓGICA DE NEGOCIO)
-- =========================================================================

-- FUNCIÓN 1: LOGIN CENTRALIZADO
CREATE OR REPLACE FUNCTION fn_login_centralizado (
    p_username VARCHAR2,
    p_password_text VARCHAR2
) RETURN NUMBER IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_stored_hash VARCHAR2(64);
    v_usuario_id NUMBER;
    v_intentos NUMBER;
BEGIN
    BEGIN
        SELECT usuario_id, password_hash, intentos_fallidos 
        INTO v_usuario_id, v_stored_hash, v_intentos
        FROM Usuario_Sistema 
        WHERE username = p_username AND estado = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN 0;
    END;

    IF v_intentos >= 5 THEN
        RETURN -1; -- Cuenta Bloqueada
    END IF;
    
    IF v_stored_hash = RAWTOHEX(DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW(p_password_text, 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256)) THEN
        UPDATE Usuario_Sistema 
        SET ultimo_acceso = CURRENT_TIMESTAMP, 
            intentos_fallidos = 0 
        WHERE usuario_id = v_usuario_id;
        COMMIT;
        RETURN 1;
    ELSE
        UPDATE Usuario_Sistema 
        SET intentos_fallidos = intentos_fallidos + 1 
        WHERE usuario_id = v_usuario_id;
        COMMIT;
        RETURN 0;
    END IF;
END;
/

-- PROCEDIMIENTO 1: Actualizar Foto de Perfil (NUEVO V3.2)
CREATE OR REPLACE PROCEDURE sp_actualizar_foto_usuario (
    p_usuario_id NUMBER,
    p_foto_blob BLOB,
    p_mime_type VARCHAR2,
    p_nombre_archivo VARCHAR2
) AS
BEGIN
    UPDATE Usuario_Sistema
    SET foto_perfil = p_foto_blob,
        foto_mime_type = p_mime_type,
        foto_nombre = p_nombre_archivo
    WHERE usuario_id = p_usuario_id;
    COMMIT;
END;
/

-- PROCEDIMIENTO 2: Crear Orden de Compra
CREATE OR REPLACE PROCEDURE sp_registrar_compra_completa (
    p_afiliado_id NUMBER,
    p_usuario_creador NUMBER,
    p_fecha_entrega DATE,
    p_detalles SYS_REFCURSOR
) AS
    v_orden_id NUMBER;
    v_prod_id NUMBER;
    v_cant NUMBER;
    v_precio NUMBER;
    v_total NUMBER := 0;
BEGIN
    INSERT INTO Orden_Compra (afiliado_id, usuario_creacion_id, fecha_entrega_prevista, estado)
    VALUES (p_afiliado_id, p_usuario_creador, p_fecha_entrega, 0)
    RETURNING orden_compra_id INTO v_orden_id;

    LOOP
        FETCH p_detalles INTO v_prod_id, v_cant, v_precio;
        EXIT WHEN p_detalles%NOTFOUND;
        
        INSERT INTO Detalle_Orden (orden_compra_id, producto_id, cantidad, precio_unitario, subtotal)
        VALUES (v_orden_id, v_prod_id, v_cant, v_precio, (v_cant * v_precio));
        
        v_total := v_total + (v_cant * v_precio);
    END LOOP;
    
    UPDATE Orden_Compra SET total = v_total WHERE orden_compra_id = v_orden_id;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- PROCEDIMIENTO 3: Procesar Recepción (BLOB)
CREATE OR REPLACE PROCEDURE sp_procesar_recepcion (
    p_envio_id NUMBER,
    p_comite_miembro_id NUMBER,
    p_observaciones VARCHAR2,
    p_acta_blob BLOB,      
    p_acta_mime VARCHAR2,  
    p_acta_nombre VARCHAR2 
) AS
BEGIN
    INSERT INTO Recepcion (
        envio_id, 
        comite_miembro_id, 
        estado_conformidad, 
        observaciones_generales, 
        acta_archivo, 
        acta_mime_type, 
        acta_nombre_archivo
    )
    VALUES (
        p_envio_id, 
        p_comite_miembro_id, 
        'CONFORME', 
        p_observaciones, 
        p_acta_blob, 
        p_acta_mime, 
        p_acta_nombre
    );
    
    UPDATE Envio SET estado_envio = 'ENTREGADO' WHERE envio_id = p_envio_id;
    COMMIT;
END;
/